### ISSUE TITLE
Extending Blazorade Mermaid

### ISSUE THREAD

**Issue by MikaBerglund** [frankhaugen/Frank.Blazor.Mermaid#1]
Hi Frank!

I came across your Blazor Mermaid wrapper project, and read that you wrote that so that you could specify the diagram definition as child content of the `MermaidDiagram` component, instead of setting a parameter.

I think that can be useful in some cases, and does not conflict with other design ideas for Blazorade Mermaid, so I [wrote an issue](https://github.com/Blazorade/Blazorade-Mermaid/issues/14) about it in [Blazorade Mermaid](https://github.com/Blazorade/Blazorade-Mermaid), and will probably at some point start working on it.

Just thought you might want to know, and thanks for the idea!

**Comment by frankhaugen** [comment]
> Just thought you might want to know, and thanks for the idea!

Thank you very much for letting me know; it's just the sort of mood-booster I needed right now 😄
